# Generated by Django 4.1.2 on 2022-10-28 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLevelFrames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.CharField(max_length=150, verbose_name='Фрейм')),
            ],
            options={
                'verbose_name': 'Фрейм 1 уровня',
                'verbose_name_plural': 'Фреймы 1 уровня',
            },
        ),
        migrations.CreateModel(
            name='ProjectGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Группа_проекта')),
                ('url', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Группа проекта',
                'verbose_name_plural': 'Группы проекта',
            },
        ),
        migrations.CreateModel(
            name='ProjectLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, verbose_name='Язык_проекта')),
                ('url', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Язык проекта',
                'verbose_name_plural': 'Языки проекта',
            },
        ),
        migrations.CreateModel(
            name='ProjectMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО_участника')),
                ('project_position', models.CharField(blank=True, max_length=150, verbose_name='Должность_в_проекте')),
                ('link_on_member', models.CharField(blank=True, max_length=150, verbose_name='Ссылка_на_основную_страницу')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проекта',
            },
        ),
        migrations.CreateModel(
            name='ProjectPublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название_публикации')),
                ('description', models.TextField(default='', verbose_name='Описание_публикации')),
                ('information', models.TextField(default='', verbose_name='Информация_о_публикации')),
                ('year', models.PositiveSmallIntegerField(blank=True, verbose_name='Дата_публикации')),
                ('work_file', models.FileField(blank=True, upload_to='publications/')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('languages', models.ManyToManyField(blank=True, to='projects.projectlanguages')),
                ('members', models.ManyToManyField(blank=True, to='projects.projectmembers')),
            ],
            options={
                'verbose_name': 'Публикация проекта',
                'verbose_name_plural': 'Публикации проекта',
            },
        ),
        migrations.CreateModel(
            name='ProjectQualificationWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название_работы')),
                ('degree', models.CharField(blank=True, max_length=150, verbose_name='Научная_степень')),
                ('university', models.CharField(blank=True, max_length=150, verbose_name='Университет_защиты')),
                ('year', models.PositiveSmallIntegerField(blank=True, verbose_name='Дата_публикации')),
                ('work_file', models.FileField(blank=True, upload_to='qualific_works/')),
                ('author', models.ManyToManyField(blank=True, to='projects.projectmembers')),
            ],
            options={
                'verbose_name': 'Квалификационная работа проекта',
                'verbose_name_plural': 'Квалификационные работы проекта',
            },
        ),
        migrations.CreateModel(
            name='ProjectSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название_бд')),
            ],
        ),
        migrations.CreateModel(
            name='SearchLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=150, verbose_name='Язык')),
                ('author', models.CharField(max_length=150, verbose_name='Сборщик данных')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='SecondLevelFrames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_frame', models.CharField(max_length=150, verbose_name='Фрейм')),
                ('frame_image', models.FileField(blank=True, upload_to='images/', verbose_name='Изображение')),
                ('parent_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.firstlevelframes', verbose_name='Родительский фрейм')),
            ],
            options={
                'verbose_name': 'Фрейм 2 уровня',
                'verbose_name_plural': 'Фреймы 2 уровня',
            },
        ),
        migrations.CreateModel(
            name='SearchObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150, verbose_name='Слово')),
                ('translation', models.CharField(max_length=150, verbose_name='Перевод')),
                ('construction', models.CharField(blank=True, max_length=150, null=True, verbose_name='Конструкция')),
                ('comment', models.TextField(blank=True, null=True)),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.firstlevelframes')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.searchlanguages')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectsearch')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название_проекта')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('short_description', models.TextField(default='', verbose_name='Краткое_описание')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectgroups', verbose_name='Группа')),
                ('language', models.ManyToManyField(blank=True, to='projects.projectlanguages')),
                ('members', models.ManyToManyField(blank=True, to='projects.projectmembers')),
                ('publications', models.ManyToManyField(blank=True, to='projects.projectpublications')),
                ('qualification_works', models.ManyToManyField(blank=True, to='projects.projectqualificationworks')),
                ('search_database', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectsearch')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectQuestionnaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название_анкеты')),
                ('work_file', models.FileField(blank=True, upload_to='questionnaires/')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projects')),
            ],
            options={
                'verbose_name': 'Анкета проекта',
                'verbose_name_plural': 'Анкеты проекта',
            },
        ),
        migrations.CreateModel(
            name='Metaphors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaphor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Метафора')),
                ('ex_metaphor', models.CharField(max_length=150, verbose_name='Пример метафоры')),
                ('metaphor_translation', models.CharField(max_length=150, verbose_name='Перевод метафоры')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.searchobjects')),
            ],
            options={
                'verbose_name': 'Метафора',
                'verbose_name_plural': 'Метафоры',
            },
        ),
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eg', models.CharField(max_length=150, verbose_name='Пример использования')),
                ('eg_translation', models.CharField(max_length=150, verbose_name='Перевод примера')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.searchobjects')),
            ],
            options={
                'verbose_name': 'Пример использования',
                'verbose_name_plural': 'Примеры использования',
            },
        ),
    ]
