# Generated by Django 4.1.2 on 2022-10-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectsearch_url_alter_searchlanguages_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsearch',
            name='url',
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
