# Generated by Django 4.1.2 on 2022-10-30 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectsearch_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlanguages',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectsearch'),
        ),
    ]
