# Generated by Django 4.1.2 on 2022-10-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_searchlanguages_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstlevelframes',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectsearch'),
        ),
    ]
