# Generated by Django 4.1.2 on 2022-10-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_firstlevelframes_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchobjects',
            name='construction_is',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
